---
- hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3.5
    tor_AbuseEmailAddress: "abuse@example.com"
    tor_ContactInfo: "toradmin@example.com"
    tor_ExitRelay: True
    tor_exit_notice_file: "exit-notice/tor-exit-notice.html"
    tor_ExitNoticePage: True
    tor_signingkeylifetime_days: 180
    tor_ports:
      - orport: 9000
        dirport: 80
      - orport: 9100
        dirport: 81
  roles:
    - nusenu.relayor
