---
- hosts: all
  vars:
    tor_ContactInfo: "toradmin@example.com"
    ansible_python_interpreter: /usr/bin/python3.5
    tor_DisableNetwork: 1
    tor_PublishServerDescriptor: 0
  roles:
    - nusenu.relayor
